import 'dart:convert';
import 'dart:typed_data';
import 'package:archive/archive.dart';

/// Generates valid Microsoft Word (.docx) documents from markdown / structured text
class DocxArtifactGenerator {
  /// Converts text / markdown to a standard OpenXML (.docx) zip file
  static Uint8List generateDocx({
    required String title,
    String? subtitle,
    required String content,
    String? author,
  }) {
    final archive = Archive();

    // 1. [Content_Types].xml
    archive.addFile(ArchiveFile(
      '[Content_Types].xml',
      _contentTypesXml.length,
      utf8.encode(_contentTypesXml),
    ));

    // 2. _rels/.rels
    archive.addFile(ArchiveFile(
      '_rels/.rels',
      _relsXml.length,
      utf8.encode(_relsXml),
    ));

    // 3. word/_rels/document.xml.rels
    archive.addFile(ArchiveFile(
      'word/_rels/document.xml.rels',
      _documentRelsXml.length,
      utf8.encode(_documentRelsXml),
    ));

    // 4. word/styles.xml
    archive.addFile(ArchiveFile(
      'word/styles.xml',
      _stylesXml.length,
      utf8.encode(_stylesXml),
    ));

    // 5. word/document.xml
    final docXml = _buildDocumentXml(
      title: title,
      subtitle: subtitle,
      content: content,
      author: author,
    );
    archive.addFile(ArchiveFile(
      'word/document.xml',
      docXml.length,
      utf8.encode(docXml),
    ));

    final zipEncoder = ZipEncoder();
    final zipped = zipEncoder.encode(archive);
    return Uint8List.fromList(zipped);
  }

  static String _buildDocumentXml({
    required String title,
    String? subtitle,
    required String content,
    String? author,
  }) {
    final buffer = StringBuffer();
    buffer.write('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>');
    buffer.write('<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">');
    buffer.write('<w:body>');

    // Title Paragraph
    buffer.write('<w:p>');
    buffer.write('<w:pPr><w:pStyle w:val="Title"/><w:jc w:val="left"/></w:pPr>');
    buffer.write('<w:r>');
    buffer.write('<w:rPr><w:b/><w:sz w:val="48"/><w:color w:val="8A3B14"/></w:rPr>');
    buffer.write('<w:t>${_escapeXml(title)}</w:t>');
    buffer.write('</w:r>');
    buffer.write('</w:p>');

    // Subtitle
    if (subtitle != null && subtitle.isNotEmpty) {
      buffer.write('<w:p>');
      buffer.write('<w:pPr><w:pStyle w:val="Subtitle"/></w:pPr>');
      buffer.write('<w:r>');
      buffer.write('<w:rPr><w:i/><w:sz w:val="24"/><w:color w:val="666666"/></w:rPr>');
      buffer.write('<w:t>${_escapeXml(subtitle)}</w:t>');
      buffer.write('</w:r>');
      buffer.write('</w:p>');
    }

    // Metadata line
    buffer.write('<w:p>');
    buffer.write('<w:pPr><w:jc w:val="left"/></w:pPr>');
    buffer.write('<w:r>');
    buffer.write('<w:rPr><w:sz w:val="18"/><w:color w:val="999999"/></w:rPr>');
    buffer.write('<w:t>Generated by AIRA-OS • ${DateTime.now().toLocal().toString().substring(0, 10)}</w:t>');
    buffer.write('</w:r>');
    buffer.write('</w:p>');

    // Divider line
    buffer.write('<w:p><w:pPr><w:pBdr><w:bottom w:val="single" w:sz="12" w:space="4" w:color="8A3B14"/></w:pBdr></w:pPr></w:p>');

    // Body parsing
    final lines = content.split('\n');
    List<List<String>> tableBuffer = [];
    bool inTable = false;

    for (int i = 0; i < lines.length; i++) {
      final rawLine = lines[i].trim();

      // Table detection
      if (rawLine.startsWith('|') && rawLine.endsWith('|')) {
        inTable = true;
        if (rawLine.contains('---')) continue;
        final cells = rawLine.split('|').map((c) => c.trim()).where((c) => c.isNotEmpty).toList();
        if (cells.isNotEmpty) tableBuffer.add(cells);
        continue;
      } else if (inTable) {
        if (tableBuffer.isNotEmpty) {
          buffer.write(_renderDocxTable(tableBuffer));
          tableBuffer = [];
        }
        inTable = false;
      }

      if (rawLine.isEmpty) {
        buffer.write('<w:p/>');
        continue;
      }

      if (rawLine.startsWith('# ')) {
        buffer.write(_renderHeading(rawLine.substring(2).trim(), 36, "8A3B14"));
      } else if (rawLine.startsWith('## ')) {
        buffer.write(_renderHeading(rawLine.substring(3).trim(), 28, "2E3440"));
      } else if (rawLine.startsWith('### ')) {
        buffer.write(_renderHeading(rawLine.substring(4).trim(), 24, "4C566A"));
      } else if (rawLine.startsWith('- ') || rawLine.startsWith('* ')) {
        buffer.write(_renderBullet(rawLine.substring(2).trim()));
      } else if (rawLine.startsWith('> ')) {
        buffer.write(_renderCallout(rawLine.substring(2).trim()));
      } else {
        buffer.write(_renderParagraph(rawLine));
      }
    }

    if (tableBuffer.isNotEmpty) {
      buffer.write(_renderDocxTable(tableBuffer));
    }

    buffer.write('</w:body>');
    buffer.write('</w:document>');
    return buffer.toString();
  }

  static String _renderHeading(String text, int sz, String color) {
    return '<w:p><w:pPr><w:spacing w:before="240" w:after="120"/></w:pPr>'
        '<w:r><w:rPr><w:b/><w:sz w:val="$sz"/><w:color w:val="$color"/></w:rPr>'
        '<w:t>${_escapeXml(text)}</w:t></w:r></w:p>';
  }

  static String _renderBullet(String text) {
    return '<w:p><w:pPr><w:ind w:left="720"/><w:spacing w:after="80"/></w:pPr>'
        '<w:r><w:rPr><w:color w:val="8A3B14"/></w:rPr><w:t>• </w:t></w:r>'
        '<w:r><w:rPr><w:sz w:val="22"/><w:color w:val="222222"/></w:rPr>'
        '<w:t>${_escapeXml(text)}</w:t></w:r></w:p>';
  }

  static String _renderCallout(String text) {
    return '<w:p><w:pPr>'
        '<w:pBdr><w:left w:val="single" w:sz="24" w:space="12" w:color="8A3B14"/></w:pBdr>'
        '<w:ind w:left="360"/><w:spacing w:before="120" w:after="120"/>'
        '</w:pPr>'
        '<w:r><w:rPr><w:i/><w:sz w:val="20"/><w:color w:val="555555"/></w:rPr>'
        '<w:t>${_escapeXml(text)}</w:t></w:r></w:p>';
  }

  static String _renderParagraph(String text) {
    return '<w:p><w:pPr><w:spacing w:after="120"/><w:jc w:val="both"/></w:pPr>'
        '<w:r><w:rPr><w:sz w:val="22"/><w:color w:val="333333"/></w:rPr>'
        '<w:t>${_escapeXml(text)}</w:t></w:r></w:p>';
  }

  static String _renderDocxTable(List<List<String>> tableData) {
    final sb = StringBuffer();
    sb.write('<w:tbl>');
    sb.write('<w:tblPr>');
    sb.write('<w:tblBorders>');
    sb.write('<w:top w:val="single" w:sz="6" w:space="0" w:color="CCCCCC"/>');
    sb.write('<w:left w:val="none"/>');
    sb.write('<w:bottom w:val="single" w:sz="6" w:space="0" w:color="CCCCCC"/>');
    sb.write('<w:right w:val="none"/>');
    sb.write('<w:insideH w:val="single" w:sz="4" w:space="0" w:color="E0E0E0"/>');
    sb.write('<w:insideV w:val="none"/>');
    sb.write('</w:tblBorders>');
    sb.write('</w:tblPr>');

    for (int r = 0; r < tableData.length; r++) {
      final row = tableData[r];
      final isHeader = r == 0;
      sb.write('<w:tr>');
      for (final cell in row) {
        sb.write('<w:tc>');
        sb.write('<w:tcPr>');
        if (isHeader) {
          sb.write('<w:shd w:val="clear" w:color="auto" w:fill="F5F3EF"/>');
        }
        sb.write('</w:tcPr>');
        sb.write('<w:p>');
        sb.write('<w:r>');
        sb.write('<w:rPr>');
        if (isHeader) sb.write('<w:b/>');
        sb.write('<w:sz w:val="20"/>');
        sb.write('<w:color w:val="${isHeader ? '8A3B14' : '333333'}"/>');
        sb.write('</w:rPr>');
        sb.write('<w:t>${_escapeXml(cell)}</w:t>');
        sb.write('</w:r>');
        sb.write('</w:p>');
        sb.write('</w:tc>');
      }
      sb.write('</w:tr>');
    }
    sb.write('</w:tbl>');
    return sb.toString();
  }

  static String _escapeXml(String text) {
    return text
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;')
        .replaceAll('"', '&quot;')
        .replaceAll("'", '&apos;');
  }

  static const _contentTypesXml = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
  <Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>
</Types>''';

  static const _relsXml = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>''';

  static const _documentRelsXml = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
</Relationships>''';

  static const _stylesXml = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:docDefaults>
    <w:rPrDefault>
      <w:rPr>
        <w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/>
        <w:sz w:val="22"/>
      </w:rPr>
    </w:rPrDefault>
  </w:docDefaults>
</w:styles>''';
}
