import 'dart:convert';
import 'dart:typed_data';
import 'package:archive/archive.dart';
import 'package:aira_app/core/artifacts/artifact_model.dart';

/// Generates valid Microsoft PowerPoint (.pptx) presentations from slides or markdown
class PptxArtifactGenerator {
  /// Converts slide models or text to a standard OpenXML (.pptx) zip package
  static Uint8List generatePptx({
    required String title,
    String? subtitle,
    List<SlideItem>? slides,
    String? rawMarkdown,
  }) {
    final slideItems = slides ?? parseSlidesFromMarkdown(title, subtitle, rawMarkdown ?? '');
    final archive = Archive();

    // 1. [Content_Types].xml
    final contentTypes = _buildContentTypesXml(slideItems.length);
    archive.addFile(ArchiveFile(
      '[Content_Types].xml',
      contentTypes.length,
      utf8.encode(contentTypes),
    ));

    // 2. _rels/.rels
    archive.addFile(ArchiveFile(
      '_rels/.rels',
      _rootRelsXml.length,
      utf8.encode(_rootRelsXml),
    ));

    // 3. ppt/presentation.xml
    final presentationXml = _buildPresentationXml(slideItems.length);
    archive.addFile(ArchiveFile(
      'ppt/presentation.xml',
      presentationXml.length,
      utf8.encode(presentationXml),
    ));

    // 4. ppt/_rels/presentation.xml.rels
    final presRelsXml = _buildPresentationRelsXml(slideItems.length);
    archive.addFile(ArchiveFile(
      'ppt/_rels/presentation.xml.rels',
      presRelsXml.length,
      utf8.encode(presRelsXml),
    ));

    // 5. ppt/slides/slide{N}.xml
    for (int i = 0; i < slideItems.length; i++) {
      final slideXml = _buildSlideXml(slideItems[i], i + 1, slideItems.length);
      archive.addFile(ArchiveFile(
        'ppt/slides/slide${i + 1}.xml',
        slideXml.length,
        utf8.encode(slideXml),
      ));
    }

    final zipEncoder = ZipEncoder();
    final zipped = zipEncoder.encode(archive);
    return Uint8List.fromList(zipped);
  }

  /// Parses markdown into structured SlideItems
  static List<SlideItem> parseSlidesFromMarkdown(String docTitle, String? docSubtitle, String markdown) {
    final slides = <SlideItem>[];

    // Always include a Title Slide
    slides.add(SlideItem(
      title: docTitle,
      subtitle: docSubtitle ?? 'Generated by AIRA-OS Autonomous Intelligence',
      bulletPoints: const [],
    ));

    if (markdown.trim().isEmpty) return slides;

    // Split on markdown headers or slide delimiters
    final sections = markdown.split(RegExp(r'\n(?=#{1,3}\s+|---\s*\n)'));

    for (final sec in sections) {
      final lines = sec.trim().split('\n');
      if (lines.isEmpty) continue;

      String slideTitle = '';
      final bullets = <String>[];
      final notes = StringBuffer();

      for (final line in lines) {
        final trimmed = line.trim();
        if (trimmed.isEmpty || trimmed == '---') continue;

        if (trimmed.startsWith('#') && slideTitle.isEmpty) {
          slideTitle = trimmed.replaceAll(RegExp(r'^#+\s*'), '').replaceAll(RegExp(r'^Slide\s*\d*:\s*', caseSensitive: false), '').trim();
        } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
          bullets.add(trimmed.substring(2).trim());
        } else if (trimmed.toLowerCase().startsWith('notes:') || trimmed.toLowerCase().startsWith('speaker:')) {
          notes.writeln(trimmed.substring(trimmed.indexOf(':') + 1).trim());
        } else if (slideTitle.isEmpty) {
          slideTitle = trimmed;
        } else {
          bullets.add(trimmed);
        }
      }

      if (slideTitle.isNotEmpty && slideTitle.toLowerCase() != docTitle.toLowerCase()) {
        slides.add(SlideItem(
          title: slideTitle,
          bulletPoints: bullets,
          speakerNotes: notes.toString().trim().isNotEmpty ? notes.toString().trim() : null,
        ));
      }
    }

    return slides.isEmpty ? [SlideItem(title: docTitle, subtitle: docSubtitle)] : slides;
  }

  static String _buildContentTypesXml(int slideCount) {
    final sb = StringBuffer();
    sb.write('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>');
    sb.write('<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">');
    sb.write('<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>');
    sb.write('<Default Extension="xml" ContentType="application/xml"/>');
    sb.write('<Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>');
    for (int i = 1; i <= slideCount; i++) {
      sb.write('<Override PartName="/ppt/slides/slide$i.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>');
    }
    sb.write('</Types>');
    return sb.toString();
  }

  static const _rootRelsXml = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/>
</Relationships>''';

  static String _buildPresentationXml(int slideCount) {
    final sb = StringBuffer();
    sb.write('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>');
    sb.write('<p:presentation xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">');
    sb.write('<p:sldMasterIdLst/><p:sldIdLst>');
    for (int i = 1; i <= slideCount; i++) {
      sb.write('<p:sldId id="${255 + i}" r:id="rId$i"/>');
    }
    sb.write('</p:sldIdLst>');
    sb.write('<p:sldSz cx="12192000" cy="6858000" type="screen16x9"/>'); // 16:9 Widescreen standard
    sb.write('</p:presentation>');
    return sb.toString();
  }

  static String _buildPresentationRelsXml(int slideCount) {
    final sb = StringBuffer();
    sb.write('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>');
    sb.write('<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">');
    for (int i = 1; i <= slideCount; i++) {
      sb.write('<Relationship Id="rId$i" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide$i.xml"/>');
    }
    sb.write('</Relationships>');
    return sb.toString();
  }

  static String _buildSlideXml(SlideItem slide, int slideIndex, int totalSlides) {
    final sb = StringBuffer();
    sb.write('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>');
    sb.write('<p:sld xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main">');
    sb.write('<p:cSld><p:spTree>');
    sb.write('<p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>');
    sb.write('<p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>');

    // 1. Background Shape (Warm dark/terracotta accent)
    sb.write('<p:sp>');
    sb.write('<p:nvSpPr><p:cNvPr id="2" name="Slide Header Accent"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr>');
    sb.write('<p:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="12192000" cy="180000"/></a:xfrm><a:solidFill><a:srgbClr val="8A3B14"/></a:solidFill></p:spPr>');
    sb.write('</p:sp>');

    // 2. Title Box
    sb.write('<p:sp>');
    sb.write('<p:nvSpPr><p:cNvPr id="3" name="Title"/><p:cNvSpPr><a:spLocks noGrp="1"/></p:cNvSpPr><p:nvPr/></p:nvSpPr>');
    sb.write('<p:spPr><a:xfrm><a:off x="800000" y="600000"/><a:ext cx="10592000" cy="1000000"/></a:xfrm></p:spPr>');
    sb.write('<p:txBody><a:bodyPr/><a:lstStyle/><a:p>');
    sb.write('<a:pPr algn="l"/>');
    sb.write('<a:r><a:rPr lang="en-US" sz="4000" b="1"><a:solidFill><a:srgbClr val="1A1A18"/></a:solidFill><a:latin typeface="Georgia"/></a:rPr>');
    sb.write('<a:t>${_escapeXml(slide.title)}</a:t></a:r>');
    sb.write('</a:p></p:txBody>');
    sb.write('</p:sp>');

    // 3. Subtitle / Bullets Box
    sb.write('<p:sp>');
    sb.write('<p:nvSpPr><p:cNvPr id="4" name="Content"/><p:cNvSpPr><a:spLocks noGrp="1"/></p:cNvSpPr><p:nvPr/></p:nvSpPr>');
    sb.write('<p:spPr><a:xfrm><a:off x="800000" y="1800000"/><a:ext cx="10592000" cy="4200000"/></a:xfrm></p:spPr>');
    sb.write('<p:txBody><a:bodyPr/><a:lstStyle/>');

    if (slide.subtitle != null && slide.subtitle!.isNotEmpty) {
      sb.write('<a:p>');
      sb.write('<a:pPr algn="l"><a:spcBfr><a:spcPts val="1200"/></a:spcBfr></a:pPr>');
      sb.write('<a:r><a:rPr lang="en-US" sz="2400" i="1"><a:solidFill><a:srgbClr val="8A3B14"/></a:solidFill><a:latin typeface="Calibri"/></a:rPr>');
      sb.write('<a:t>${_escapeXml(slide.subtitle!)}</a:t></a:r>');
      sb.write('</a:p>');
    }

    for (final bullet in slide.bulletPoints) {
      sb.write('<a:p>');
      sb.write('<a:pPr lvl="0" algn="l"><a:buFont typeface="Arial"/><a:buChar char="•"/><a:spcBfr><a:spcPts val="1200"/></a:spcBfr></a:pPr>');
      sb.write('<a:r><a:rPr lang="en-US" sz="2200"><a:solidFill><a:srgbClr val="333333"/></a:solidFill><a:latin typeface="Calibri"/></a:rPr>');
      sb.write('<a:t>${_escapeXml(bullet)}</a:t></a:r>');
      sb.write('</a:p>');
    }

    sb.write('</p:txBody>');
    sb.write('</p:sp>');

    // 4. Slide Footer & Number
    sb.write('<p:sp>');
    sb.write('<p:nvSpPr><p:cNvPr id="5" name="Footer"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr>');
    sb.write('<p:spPr><a:xfrm><a:off x="800000" y="6200000"/><a:ext cx="10592000" cy="400000"/></a:xfrm></p:spPr>');
    sb.write('<p:txBody><a:bodyPr/><a:lstStyle/><a:p>');
    sb.write('<a:r><a:rPr lang="en-US" sz="1200"><a:solidFill><a:srgbClr val="999999"/></a:solidFill><a:latin typeface="Calibri"/></a:rPr>');
    sb.write('<a:t>AIRA-OS • Slide $slideIndex of $totalSlides</a:t></a:r>');
    sb.write('</a:p></p:txBody>');
    sb.write('</p:sp>');

    sb.write('</p:spTree></p:cSld>');
    sb.write('</p:sld>');
    return sb.toString();
  }

  static String _escapeXml(String text) {
    return text
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;')
        .replaceAll('"', '&quot;')
        .replaceAll("'", '&apos;');
  }
}
