import 'dart:convert';
import 'package:shared_preferences/shared_preferences.dart';

/// Single Time-Blocked Slot generated by AIRA Autopilot
class TimeBlockedSlot {
  final String timeRange; // e.g. "09:00 AM - 10:30 AM"
  final String title;
  final String category; // 'study', 'work', 'break', 'revision'
  final String priority;
  final bool isCompleted;

  TimeBlockedSlot({
    required this.timeRange,
    required this.title,
    required this.category,
    required this.priority,
    this.isCompleted = false,
  });

  Map<String, dynamic> toJson() => {
    'timeRange': timeRange,
    'title': title,
    'category': category,
    'priority': priority,
    'isCompleted': isCompleted,
  };
}

/// Autonomous Schedule Autopilot & Dynamic Time-Blocking Engine
class ScheduleAutopilot {
  static final ScheduleAutopilot _instance = ScheduleAutopilot._internal();
  factory ScheduleAutopilot() => _instance;
  ScheduleAutopilot._internal();

  /// Constructs an optimized, time-blocked daily schedule based on current pending tasks
  Future<List<TimeBlockedSlot>> generateOptimalSchedule() async {
    final prefs = await SharedPreferences.getInstance();
    final tasksJson = prefs.getString('aira_local_tasks_v2');
    final slots = <TimeBlockedSlot>[];

    if (tasksJson == null) {
      return _generateDefaultSlots();
    }

    try {
      final List list = jsonDecode(tasksJson);
      final pendingTasks = list.where((t) => t['isCompleted'] != true && t['status'] != 'completed').toList();

      if (pendingTasks.isEmpty) {
        return _generateDefaultSlots();
      }

      // Sort by priority (high -> medium -> low)
      pendingTasks.sort((a, b) {
        final pA = (a['priority'] as String? ?? 'medium').toLowerCase();
        final pB = (b['priority'] as String? ?? 'medium').toLowerCase();
        final scoreA = pA == 'high' ? 3 : (pA == 'medium' ? 2 : 1);
        final scoreB = pB == 'high' ? 3 : (pB == 'medium' ? 2 : 1);
        return scoreB.compareTo(scoreA);
      });

      int startHour = 9; // 9:00 AM start

      for (int i = 0; i < pendingTasks.length && i < 6; i++) {
        final task = pendingTasks[i];
        final title = task['title'] as String? ?? 'Focus Task';
        final category = task['category'] as String? ?? 'General';
        final priority = task['priority'] as String? ?? 'medium';

        final startStr = _formatHour(startHour);
        final endHour = startHour + (priority.toLowerCase() == 'high' ? 2 : 1);
        final endStr = _formatHour(endHour);

        slots.add(TimeBlockedSlot(
          timeRange: '$startStr - $endStr',
          title: title,
          category: category,
          priority: priority,
        ));

        startHour = endHour;

        // Insert break after deep work
        if (i % 2 == 1 && startHour < 17) {
          final breakEndStr = _formatHour(startHour);
          slots.add(TimeBlockedSlot(
            timeRange: '$breakEndStr - ${_formatHour(startHour + 1)}',
            title: 'Break & Refresh ☕',
            category: 'break',
            priority: 'low',
          ));
          startHour += 1;
        }
      }
    } catch (_) {
      return _generateDefaultSlots();
    }

    return slots;
  }

  List<TimeBlockedSlot> _generateDefaultSlots() {
    return [
      TimeBlockedSlot(timeRange: '09:00 AM - 11:00 AM', title: 'Core Study / Project Work', category: 'Study', priority: 'high'),
      TimeBlockedSlot(timeRange: '11:00 AM - 11:30 AM', title: 'Coffee & Refresh Break ☕', category: 'Break', priority: 'low'),
      TimeBlockedSlot(timeRange: '11:30 AM - 01:30 PM', title: 'Deep Work & Problem Solving', category: 'Work', priority: 'high'),
      TimeBlockedSlot(timeRange: '04:00 PM - 06:00 PM', title: 'Subject Revision (OS/DBMS)', category: 'Study', priority: 'medium'),
      TimeBlockedSlot(timeRange: '08:00 PM - 09:00 PM', title: 'Daily Wrap-Up & Planning', category: 'Review', priority: 'low'),
    ];
  }

  String _formatHour(int h24) {
    final period = h24 >= 12 ? 'PM' : 'AM';
    var h12 = h24 % 12;
    if (h12 == 0) h12 = 12;
    return '${h12.toString().padLeft(2, "0")}:00 $period';
  }

  /// Formats the schedule into a clean markdown card for in-chat rendering
  String formatScheduleMarkdown(List<TimeBlockedSlot> slots) {
    final buffer = StringBuffer('📅 **AIRA Autonomous Time-Blocked Schedule**\n\n');
    for (final s in slots) {
      final icon = s.category.toLowerCase() == 'break' ? '☕' : (s.priority.toLowerCase() == 'high' ? '🔥' : '⏳');
      buffer.writeln('$icon **${s.timeRange}**');
      buffer.writeln('   └─ **${s.title}** *[${s.category}]*');
    }
    buffer.writeln('\n💡 *Say "Reschedule my afternoon" or "Mark task complete" to dynamically adapt.*');
    return buffer.toString().trim();
  }
}
