import 'dart:typed_data';

/// Supported Claude-Style GenAI Artifact Types in AIRA-OS
enum ArtifactType {
  pdf,
  docx,
  pptx,
  sheet,
  csv,
  html,
  svg,
  markdown,
  code;

  String get displayName {
    switch (this) {
      case ArtifactType.pdf:
        return 'PDF Document';
      case ArtifactType.docx:
        return 'Word Document';
      case ArtifactType.pptx:
        return 'Presentation';
      case ArtifactType.sheet:
      case ArtifactType.csv:
        return 'Spreadsheet';
      case ArtifactType.html:
        return 'Interactive App';
      case ArtifactType.svg:
        return 'Vector Graphic';
      case ArtifactType.markdown:
        return 'Markdown Doc';
      case ArtifactType.code:
        return 'Code Snippet';
    }
  }

  String get fileExtension {
    switch (this) {
      case ArtifactType.pdf:
        return '.pdf';
      case ArtifactType.docx:
        return '.docx';
      case ArtifactType.pptx:
        return '.pptx';
      case ArtifactType.sheet:
      case ArtifactType.csv:
        return '.csv';
      case ArtifactType.html:
        return '.html';
      case ArtifactType.svg:
        return '.svg';
      case ArtifactType.markdown:
        return '.md';
      case ArtifactType.code:
        return '.txt';
    }
  }

  String get mimeType {
    switch (this) {
      case ArtifactType.pdf:
        return 'application/pdf';
      case ArtifactType.docx:
        return 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
      case ArtifactType.pptx:
        return 'application/vnd.openxmlformats-officedocument.presentationml.presentation';
      case ArtifactType.sheet:
      case ArtifactType.csv:
        return 'text/csv';
      case ArtifactType.html:
        return 'text/html';
      case ArtifactType.svg:
        return 'image/svg+xml';
      case ArtifactType.markdown:
        return 'text/markdown';
      case ArtifactType.code:
        return 'text/plain';
    }
  }
}

/// Represents a slide inside a PPTX presentation artifact
class SlideItem {
  final String title;
  final String? subtitle;
  final List<String> bulletPoints;
  final String? speakerNotes;

  const SlideItem({
    required this.title,
    this.subtitle,
    this.bulletPoints = const [],
    this.speakerNotes,
  });

  Map<String, dynamic> toJson() => {
        'title': title,
        'subtitle': subtitle,
        'bulletPoints': bulletPoints,
        'speakerNotes': speakerNotes,
      };

  factory SlideItem.fromJson(Map<String, dynamic> json) => SlideItem(
        title: json['title'] as String? ?? 'Slide',
        subtitle: json['subtitle'] as String?,
        bulletPoints: (json['bulletPoints'] as List<dynamic>?)
                ?.map((e) => e.toString())
                .toList() ??
            const [],
        speakerNotes: json['speakerNotes'] as String?,
      );
}

/// Represents an Artifact generated by AIRA-OS GenAI Engine
class AiraArtifact {
  final String id;
  final String title;
  final ArtifactType type;
  final String content;
  final String language;
  final Map<String, dynamic> metadata;
  final DateTime createdAt;
  final Uint8List? compiledBytes;

  const AiraArtifact({
    required this.id,
    required this.title,
    required this.type,
    required this.content,
    this.language = 'text',
    this.metadata = const {},
    required this.createdAt,
    this.compiledBytes,
  });

  AiraArtifact copyWith({
    String? id,
    String? title,
    ArtifactType? type,
    String? content,
    String? language,
    Map<String, dynamic>? metadata,
    DateTime? createdAt,
    Uint8List? compiledBytes,
  }) {
    return AiraArtifact(
      id: id ?? this.id,
      title: title ?? this.title,
      type: type ?? this.type,
      content: content ?? this.content,
      language: language ?? this.language,
      metadata: metadata ?? this.metadata,
      createdAt: createdAt ?? this.createdAt,
      compiledBytes: compiledBytes ?? this.compiledBytes,
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'title': title,
        'type': type.name,
        'content': content,
        'language': language,
        'metadata': metadata,
        'createdAt': createdAt.toIso8601String(),
      };

  factory AiraArtifact.fromJson(Map<String, dynamic> json) => AiraArtifact(
        id: json['id'] as String? ?? '',
        title: json['title'] as String? ?? 'Untitled Artifact',
        type: ArtifactType.values.firstWhere(
          (t) => t.name == (json['type'] as String? ?? 'code'),
          orElse: () => ArtifactType.code,
        ),
        content: json['content'] as String? ?? '',
        language: json['language'] as String? ?? 'text',
        metadata: (json['metadata'] as Map<String, dynamic>?) ?? const {},
        createdAt: DateTime.tryParse(json['createdAt'] as String? ?? '') ??
            DateTime.now(),
      );
}
