import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:aira_app/core/theme/aira_colors.dart';
import 'package:aira_app/core/artifacts/artifact_model.dart';
import 'package:aira_app/core/artifacts/artifact_service.dart';
import 'package:aira_app/core/artifacts/generators/csv_generator.dart';

class ArtifactCanvasScreen extends StatefulWidget {
  final String title;
  final String content;
  final String language;
  final AiraArtifact? artifact;

  const ArtifactCanvasScreen({
    super.key,
    required this.title,
    required this.content,
    this.language = 'code',
    this.artifact,
  });

  @override
  State<ArtifactCanvasScreen> createState() => _ArtifactCanvasScreenState();
}

class _ArtifactCanvasScreenState extends State<ArtifactCanvasScreen> {
  late bool _showPreview;
  final bool _showLineNumbers = true;
  bool _isExporting = false;
  int _currentSlideIndex = 0;
  List<SlideItem> _slides = [];

  late AiraArtifact _effectiveArtifact;

  @override
  void initState() {
    super.initState();
    _effectiveArtifact = widget.artifact ??
        AiraArtifact(
          id: 'art_${DateTime.now().millisecondsSinceEpoch}',
          title: widget.title,
          type: _inferType(widget.language),
          content: widget.content,
          language: widget.language,
          createdAt: DateTime.now(),
        );

    _showPreview = _effectiveArtifact.type != ArtifactType.code;

    if (_effectiveArtifact.type == ArtifactType.pptx) {
      _parsePptxSlides();
    }
  }

  void _parsePptxSlides() {
    final sections = _effectiveArtifact.content.split(RegExp(r'\n(?=#{1,3}\s+|---\s*\n)'));
    final list = <SlideItem>[];

    list.add(SlideItem(
      title: _effectiveArtifact.title,
      subtitle: 'Generated by AIRA-OS GenAI Engine',
      bulletPoints: const [],
    ));

    for (final sec in sections) {
      final lines = sec.trim().split('\n');
      if (lines.isEmpty) continue;
      String slideTitle = '';
      final bullets = <String>[];
      String? notes;

      for (final line in lines) {
        final trimmed = line.trim();
        if (trimmed.isEmpty || trimmed == '---') continue;
        if (trimmed.startsWith('#') && slideTitle.isEmpty) {
          slideTitle = trimmed.replaceAll(RegExp(r'^#+\s*'), '').trim();
        } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
          bullets.add(trimmed.substring(2).trim());
        } else if (trimmed.toLowerCase().startsWith('notes:')) {
          notes = trimmed.substring(6).trim();
        } else if (slideTitle.isEmpty) {
          slideTitle = trimmed;
        } else {
          bullets.add(trimmed);
        }
      }

      if (slideTitle.isNotEmpty && slideTitle != _effectiveArtifact.title) {
        list.add(SlideItem(title: slideTitle, bulletPoints: bullets, speakerNotes: notes));
      }
    }

    setState(() {
      _slides = list.isEmpty ? [SlideItem(title: _effectiveArtifact.title)] : list;
    });
  }

  ArtifactType _inferType(String lang) {
    final lower = lang.toLowerCase();
    if (lower.contains('pdf')) return ArtifactType.pdf;
    if (lower.contains('docx') || lower.contains('doc') || lower.contains('word')) return ArtifactType.docx;
    if (lower.contains('pptx') || lower.contains('ppt') || lower.contains('slide')) return ArtifactType.pptx;
    if (lower.contains('csv') || lower.contains('sheet')) return ArtifactType.csv;
    if (lower.contains('html')) return ArtifactType.html;
    if (lower.contains('svg')) return ArtifactType.svg;
    if (lower.contains('md') || lower.contains('markdown')) return ArtifactType.markdown;
    return ArtifactType.code;
  }

  Future<void> _downloadArtifact() async {
    setState(() => _isExporting = true);
    try {
      final path = await ArtifactService().saveArtifactLocally(_effectiveArtifact);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Row(
              children: [
                const Icon(Icons.check_circle_rounded, color: Colors.white, size: 18),
                const SizedBox(width: 8),
                Expanded(
                  child: Text(
                    'Saved to $path',
                    style: GoogleFonts.sourceSerif4(fontSize: 12),
                  ),
                ),
              ],
            ),
            backgroundColor: const Color(0xFF1E8E3E),
            behavior: SnackBarBehavior.floating,
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to save file: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) setState(() => _isExporting = false);
    }
  }

  Future<void> _exportToGoogleDrive() async {
    setState(() => _isExporting = true);
    try {
      final res = await ArtifactService().exportToGoogleDrive(_effectiveArtifact);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(res['success'] == true
                ? 'Uploaded ${_effectiveArtifact.title} to Google Drive!'
                : 'Drive upload note: ${res['error'] ?? 'Saved'}'),
            backgroundColor: AiraColors.claudeTerracotta,
            behavior: SnackBarBehavior.floating,
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Drive export error: $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _isExporting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;

    return Scaffold(
      backgroundColor: isDark ? const Color(0xFF141311) : const Color(0xFFFAF9F5),
      appBar: AppBar(
        backgroundColor: isDark ? const Color(0xFF1C1B18) : const Color(0xFFF3F1EC),
        elevation: 0,
        leading: IconButton(
          icon: Icon(Icons.close_rounded, color: theme.colorScheme.onSurface, size: 22),
          onPressed: () => Navigator.pop(context),
        ),
        title: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              _effectiveArtifact.title,
              style: GoogleFonts.sourceSerif4(
                fontWeight: FontWeight.w700,
                fontSize: 16,
                color: theme.colorScheme.onSurface,
              ),
              overflow: TextOverflow.ellipsis,
            ),
            Row(
              children: [
                Text(
                  _effectiveArtifact.type.displayName.toUpperCase(),
                  style: GoogleFonts.sourceSerif4(
                    color: AiraColors.claudeTerracotta,
                    fontSize: 10.5,
                    fontWeight: FontWeight.w700,
                    letterSpacing: 1.0,
                  ),
                ),
                const SizedBox(width: 8),
                Text(
                  _effectiveArtifact.type.fileExtension,
                  style: GoogleFonts.firaCode(
                    color: isDark ? AiraColors.textMuted : AiraColors.textMutedLight,
                    fontSize: 10,
                  ),
                ),
              ],
            ),
          ],
        ),
        actions: [
          // Toggle Preview / Source
          IconButton(
            icon: Icon(
              _showPreview ? Icons.code_rounded : Icons.preview_rounded,
              color: theme.colorScheme.onSurface,
              size: 20,
            ),
            tooltip: _showPreview ? 'View Source Code' : 'View Formatted Preview',
            onPressed: () => setState(() => _showPreview = !_showPreview),
          ),

          // Download Action
          if (_isExporting)
            const Padding(
              padding: EdgeInsets.symmetric(horizontal: 12),
              child: SizedBox(
                width: 18,
                height: 18,
                child: CircularProgressIndicator(strokeWidth: 2, color: AiraColors.claudeTerracotta),
              ),
            )
          else
            PopupMenuButton<String>(
              icon: const Icon(Icons.download_rounded, color: AiraColors.claudeTerracotta, size: 22),
              tooltip: 'Export & Download',
              onSelected: (val) {
                if (val == 'download') _downloadArtifact();
                if (val == 'drive') _exportToGoogleDrive();
                if (val == 'copy') {
                  Clipboard.setData(ClipboardData(text: _effectiveArtifact.content));
                  ScaffoldMessenger.of(context).showSnackBar(
                    SnackBar(
                      content: Text('Copied content to clipboard'),
                      duration: const Duration(seconds: 1),
                      behavior: SnackBarBehavior.floating,
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                    ),
                  );
                }
              },
              itemBuilder: (ctx) => [
                PopupMenuItem(
                  value: 'download',
                  child: Row(
                    children: [
                      const Icon(Icons.save_alt_rounded, size: 18, color: AiraColors.claudeTerracotta),
                      const SizedBox(width: 10),
                      Text('Save to Device (${_effectiveArtifact.type.fileExtension})', style: GoogleFonts.sourceSerif4(fontSize: 13)),
                    ],
                  ),
                ),
                PopupMenuItem(
                  value: 'drive',
                  child: Row(
                    children: [
                      const Icon(Icons.cloud_upload_outlined, size: 18, color: Color(0xFF1E8E3E)),
                      const SizedBox(width: 10),
                      Text('Upload to Google Drive', style: GoogleFonts.sourceSerif4(fontSize: 13)),
                    ],
                  ),
                ),
                PopupMenuItem(
                  value: 'copy',
                  child: Row(
                    children: [
                      const Icon(Icons.copy_rounded, size: 18, color: Colors.blueGrey),
                      const SizedBox(width: 10),
                      Text('Copy Markdown Source', style: GoogleFonts.sourceSerif4(fontSize: 13)),
                    ],
                  ),
                ),
              ],
            ),
          const SizedBox(width: 6),
        ],
      ),
      body: _showPreview ? _buildPreviewBody(theme, isDark) : _buildSourceBody(theme, isDark),
    );
  }

  Widget _buildPreviewBody(ThemeData theme, bool isDark) {
    switch (_effectiveArtifact.type) {
      case ArtifactType.pptx:
        return _buildPresentationSlideViewer(theme, isDark);
      case ArtifactType.csv:
      case ArtifactType.sheet:
        return _buildDataGridTable(theme, isDark);
      case ArtifactType.pdf:
      case ArtifactType.docx:
      case ArtifactType.markdown:
      default:
        return _buildRichDocumentPreview(theme, isDark);
    }
  }

  Widget _buildRichDocumentPreview(ThemeData theme, bool isDark) {
    return SingleChildScrollView(
      padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Document Header Card
          Container(
            padding: const EdgeInsets.all(16),
            margin: const EdgeInsets.only(bottom: 20),
            decoration: BoxDecoration(
              color: isDark ? const Color(0xFF1C1B18) : const Color(0xFFF3F1EC),
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: isDark ? AiraColors.borderDark : AiraColors.borderLight),
            ),
            child: Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(10),
                  decoration: BoxDecoration(
                    color: AiraColors.claudeTerracotta.withValues(alpha: 0.15),
                    borderRadius: BorderRadius.circular(10),
                  ),
                  child: Icon(
                    _effectiveArtifact.type == ArtifactType.pdf
                        ? Icons.picture_as_pdf_rounded
                        : Icons.description_rounded,
                    color: AiraColors.claudeTerracotta,
                    size: 26,
                  ),
                ),
                const SizedBox(width: 14),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        _effectiveArtifact.title,
                        style: GoogleFonts.playfairDisplay(fontSize: 16, fontWeight: FontWeight.bold),
                      ),
                      Text(
                        'Ready for Export • ${_effectiveArtifact.type.displayName}',
                        style: GoogleFonts.sourceSerif4(
                          fontSize: 11.5,
                          color: isDark ? AiraColors.textMuted : AiraColors.textMutedLight,
                        ),
                      ),
                    ],
                  ),
                ),
                ElevatedButton.icon(
                  onPressed: _isExporting ? null : _downloadArtifact,
                  icon: const Icon(Icons.download_rounded, size: 14, color: Colors.white),
                  label: Text('Export', style: GoogleFonts.sourceSerif4(fontSize: 12, fontWeight: FontWeight.bold, color: Colors.white)),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: AiraColors.claudeTerracotta,
                    padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                  ),
                ),
              ],
            ),
          ),

          MarkdownBody(
            data: _effectiveArtifact.content,
            styleSheet: MarkdownStyleSheet(
              p: GoogleFonts.sourceSerif4(
                color: theme.colorScheme.onSurface,
                fontSize: 15,
                height: 1.6,
              ),
              h1: GoogleFonts.playfairDisplay(
                color: theme.colorScheme.onSurface,
                fontWeight: FontWeight.w700,
                fontSize: 22,
              ),
              h2: GoogleFonts.playfairDisplay(
                color: theme.colorScheme.onSurface,
                fontWeight: FontWeight.w700,
                fontSize: 19,
              ),
              blockquoteDecoration: BoxDecoration(
                color: isDark ? const Color(0xFF23201C) : const Color(0xFFF9F7F2),
                border: const Border(left: BorderSide(color: AiraColors.claudeTerracotta, width: 3)),
                borderRadius: BorderRadius.circular(6),
              ),
            ),
            selectable: true,
          ),
        ],
      ),
    );
  }

  Widget _buildPresentationSlideViewer(ThemeData theme, bool isDark) {
    if (_slides.isEmpty) {
      return Center(child: Text('No slides parsed', style: GoogleFonts.sourceSerif4()));
    }

    final slide = _slides[_currentSlideIndex];

    return Padding(
      padding: const EdgeInsets.all(16),
      child: Column(
        children: [
          // Slide Canvas Container (16:9 Aspect Ratio)
          Expanded(
            child: AspectRatio(
              aspectRatio: 16 / 9,
              child: Container(
                padding: const EdgeInsets.all(24),
                decoration: BoxDecoration(
                  color: isDark ? const Color(0xFF1E1D19) : Colors.white,
                  borderRadius: BorderRadius.circular(16),
                  border: Border.all(color: isDark ? AiraColors.borderDark : AiraColors.borderLight, width: 1.5),
                  boxShadow: [
                    BoxShadow(
                      color: Colors.black.withValues(alpha: isDark ? 0.4 : 0.08),
                      blurRadius: 16,
                      offset: const Offset(0, 6),
                    ),
                  ],
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Accent Top Bar
                    Container(
                      height: 4,
                      width: 50,
                      decoration: BoxDecoration(
                        color: AiraColors.claudeTerracotta,
                        borderRadius: BorderRadius.circular(2),
                      ),
                    ),
                    const SizedBox(height: 16),

                    // Slide Title
                    Text(
                      slide.title,
                      style: GoogleFonts.playfairDisplay(
                        fontSize: 22,
                        fontWeight: FontWeight.bold,
                        color: theme.colorScheme.onSurface,
                      ),
                    ),
                    if (slide.subtitle != null && slide.subtitle!.isNotEmpty) ...[
                      const SizedBox(height: 6),
                      Text(
                        slide.subtitle!,
                        style: GoogleFonts.sourceSerif4(
                          fontSize: 13,
                          fontStyle: FontStyle.italic,
                          color: AiraColors.claudeTerracotta,
                        ),
                      ),
                    ],
                    const SizedBox(height: 16),

                    // Bullets
                    Expanded(
                      child: ListView(
                        children: slide.bulletPoints.map((bp) {
                          return Padding(
                            padding: const EdgeInsets.only(bottom: 10),
                            child: Row(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const Padding(
                                  padding: EdgeInsets.only(top: 6, right: 10),
                                  child: Icon(Icons.circle, size: 7, color: AiraColors.claudeTerracotta),
                                ),
                                Expanded(
                                  child: Text(
                                    bp,
                                    style: GoogleFonts.sourceSerif4(
                                      fontSize: 14,
                                      height: 1.5,
                                      color: theme.colorScheme.onSurface,
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          );
                        }).toList(),
                      ),
                    ),

                    // Slide Footer
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Text('AIRA-OS Presentation', style: GoogleFonts.firaCode(fontSize: 10, color: Colors.grey)),
                        Text('Slide ${_currentSlideIndex + 1} of ${_slides.length}', style: GoogleFonts.firaCode(fontSize: 10, color: Colors.grey)),
                      ],
                    ),
                  ],
                ),
              ),
            ),
          ),

          const SizedBox(height: 14),

          // Slide Controls Bar
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
            decoration: BoxDecoration(
              color: isDark ? const Color(0xFF1C1B18) : const Color(0xFFF3F1EC),
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: isDark ? AiraColors.borderDark : AiraColors.borderLight),
            ),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                IconButton(
                  icon: const Icon(Icons.arrow_back_ios_rounded, size: 16),
                  onPressed: _currentSlideIndex > 0
                      ? () => setState(() => _currentSlideIndex--)
                      : null,
                ),
                Text(
                  'Slide ${_currentSlideIndex + 1} of ${_slides.length}',
                  style: GoogleFonts.sourceSerif4(fontWeight: FontWeight.bold, fontSize: 13),
                ),
                IconButton(
                  icon: const Icon(Icons.arrow_forward_ios_rounded, size: 16),
                  onPressed: _currentSlideIndex < _slides.length - 1
                      ? () => setState(() => _currentSlideIndex++)
                      : null,
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildDataGridTable(ThemeData theme, bool isDark) {
    final rows = CsvArtifactGenerator.parseMarkdownTable(_effectiveArtifact.content);
    if (rows.isEmpty) {
      return Center(child: Text('No tabular data detected', style: GoogleFonts.sourceSerif4()));
    }

    final headers = rows.first;
    final dataRows = rows.skip(1).toList();

    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      scrollDirection: Axis.horizontal,
      child: SingleChildScrollView(
        child: DataTable(
          headingRowColor: WidgetStatePropertyAll(
            isDark ? const Color(0xFF2C2520) : const Color(0xFFEFE8DF),
          ),
          columns: headers
              .map((h) => DataColumn(
                    label: Text(
                      h,
                      style: GoogleFonts.playfairDisplay(fontWeight: FontWeight.bold, fontSize: 13),
                    ),
                  ))
              .toList(),
          rows: dataRows
              .map((r) => DataRow(
                    cells: r
                        .map((cell) => DataCell(
                              Text(cell, style: GoogleFonts.firaCode(fontSize: 12)),
                            ))
                        .toList(),
                  ))
              .toList(),
        ),
      ),
    );
  }

  Widget _buildSourceBody(ThemeData theme, bool isDark) {
    final lines = _effectiveArtifact.content.split('\n');

    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Container(
        width: double.infinity,
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: isDark ? const Color(0xFF1E1D1A) : const Color(0xFFFFFFFF),
          borderRadius: BorderRadius.circular(14),
          border: Border.all(color: isDark ? AiraColors.borderDark : AiraColors.borderLight),
        ),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            if (_showLineNumbers)
              Padding(
                padding: const EdgeInsets.only(right: 14),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.end,
                  children: List.generate(lines.length, (index) {
                    return Text(
                      '${index + 1}',
                      style: GoogleFonts.firaCode(
                        fontSize: 13,
                        color: isDark ? Colors.white24 : Colors.black26,
                        height: 1.5,
                      ),
                    );
                  }),
                ),
              ),
            Expanded(
              child: SelectableText(
                _effectiveArtifact.content,
                style: GoogleFonts.firaCode(
                  fontSize: 13,
                  color: isDark ? const Color(0xFFECEBE6) : const Color(0xFF1E1E1C),
                  height: 1.5,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
